# Generated by Django 3.2.1 on 2021-05-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Department_Name',
            new_name='department_name',
        ),
    ]
