# Generated by Django 3.2.1 on 2021-05-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0002_rename_department_name_department_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='departmentname',
        ),
    ]
