# Generated by Django 3.2.1 on 2021-05-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departments', '0001_initial'),
        ('Providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=150)),
                ('Product_Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Product_ID', models.CharField(max_length=50)),
                ('Product_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.department')),
                ('Provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Providers.provider')),
            ],
        ),
    ]
