# Generated by Django 3.2.1 on 2021-05-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_product_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_Description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_ID',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_Name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_Price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Provider',
            new_name='provider',
        ),
    ]
