# Generated by Django 3.2.1 on 2021-05-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20210511_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='productdescription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='productid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='productprice',
        ),
    ]
