# Generated by Django 3.2.1 on 2021-05-15 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employes', '0003_alter_employe_secondname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='usr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usremploye', to=settings.AUTH_USER_MODEL),
        ),
    ]
