# Generated by Django 3.2.1 on 2021-05-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Providers', '0002_rename_provider_name_provider_provider_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='provider_name',
            new_name='providername',
        ),
    ]
